<a href="https://colab.research.google.com/github/GianmarcoLattaruolo/Vision_Project/blob/main/NewDataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Our dataset

We have downloaded a new 10k dataset with gps coordinates. We need the labels for the scenes.

In [ ]:
import numpy as np
import importlib
imported_module = importlib.import_module("scene_classification")
importlib.reload(imported_module)
import scene_classification
from scene_classification import SceneClassifier

In [ ]:
import pandas as pd

#initialiaze the classifier
scene_classifier = SceneClassifier(runtime='cpu')

#list of the images with full path
path = r'/content/drive/MyDrive/GeoEstimation/resources/images/new_data10k'
path_list = os.listdir(path)
path_list = [path+'/'+im for im in path_list if im[-3:]=='jpg']
print('num of images is ' , len(path_list))

#original file csv with images info
data_10k = pd.read_csv(r'/content/drive/MyDrive/GeoEstimation/resources/images/final_dataset_10k.csv', sep=';')
print('the origninal df of images info is')
display(data_10k.head())

#classification of the images, producing both S3_labels that probs
places_prob, S3_labels = scene_classifier.process_images(path_list,b_size=128)
print('num of triplette of probabilities is ' , len(places_prob))
print('num of  S3_labels is ', len(S3_labels))

#new file csv formation
new_data = pd.DataFrame(data = np.asarray(places_prob), columns=['Prob_indoor','Prob_natural','Prob_urban'])
S3_labels_data =  pd.DataFrame(data = np.asarray([S3_labels]).T ,columns=['S3_label'])
images_name = [im[:-4] for im in os.listdir(path) if im[-3:]=='jpg']
images_name_df = pd.DataFrame(data = images_name ,  columns=['photo_id'])

#new df with the new information
new_df = pd.concat([images_name_df,S3_labels_data,new_data],axis=1)
print('the new data column we have now are')
display(new_df.head(20))

#final merge with the original csv
data_10k['photo_id']=data_10k['photo_id'].apply(lambda x: str(x))
new_df_full = data_10k.merge(right = new_df, on='photo_id')
print('final DataFrame')
new_df_full['photo_id'] = new_df_full['photo_id'].apply(lambda x: x+'.jpg') 
new_df_full.drop(new_df_full.columns[new_df_full.columns.str.contains('unnamed',case = False)],axis = 1, inplace = True)
new_df_full.head()

#save the new dataframe in a csv
print("Let's save the results")
new_df_full.to_csv(path_or_buf=r'/content/drive/MyDrive/GeoEstimation/resources/images/data10k_places365.csv', index=False, sep=',')

Loading scene hierarchy ...
num of images is  9446
the origninal df of images info is

,Unnamed: 0,photo_id,owner,gender,occupation,title,description,faves,lat,lon,u_city,u_country,taken,weather,season,daytime,base_url,url
0,0,17271526139,130418712@N05,1.0,NaN,Rio Trejo,Son numerosos los rios y arroyos que discurren...,701.0,"36,861544","-5,177747",NaN,NaN,2015-04-26 17:11:11,NaN,1.0,2.0,https://www.flickr.com/photos/130418712@N05/17...,https://live.staticflickr.com/65535/1727152613...
1,1,17776887679,55101137@N02,1.0,NaN,2015-05-13-022FD PH-XRD,<u><b>Aircraft Type - Registration - (c/n)</b>...,1.0,"51,463766","5,392935",Bodmin,United Kingdom,2015-05-13 00:00:22,9.0,1.0,3.0,https://www.flickr.com/photos/55101137@N02/177...,https://live.staticflickr.com/5335/17776887679...
2,2,17898331633,55101137@N02,1.0,NaN,2015-05-17-022FD OO-GWA,<u><b>Aircraft Type - Registration - (c/n)</b>...,2.0,"51,190492","4,453765",Bodmin,United Kingdom,2015-05-17 00:00:22,9.0,1.0,3.0,https://www.flickr.com/photos/55101137@N02/178...,https://live.staticflickr.com/525/17898331633_...
3,3,17940239919,55101137@N02,1.0,NaN,2015-05-14-020FD D-1553,<u><b>Aircraft Type - Registration - (c/n)</b>...,0.0,"51,326247","6,085953",Bodmin,United Kingdom,2015-05-14 00:00:20,9.0,1.0,3.0,https://www.flickr.com/photos/55101137@N02/179...,https://live.staticflickr.com/8860/17940239919...
4,4,17963122505,55101137@N02,1.0,NaN,2015-05-13-025FD EI-DLI,<u><b>Aircraft Type - Registration - (c/n)</b>...,2.0,"51,463766","5,392935",Bodmin,United Kingdom,2015-05-13 00:00:25,9.0,1.0,3.0,https://www.flickr.com/photos/55101137@N02/179...,https://live.staticflickr.com/5457/17963122505...

We have 74 batches
We are at batch  1
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  2
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  3
this batch has size  torch.Size([127, 3, 256, 256])
We are at batch  4
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  5
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  6
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  7
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  8
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  9
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  10
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  11
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  12
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  13
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  14
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  15
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  16
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  17
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  18
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  19
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  20
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  21
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  22
this batch has size  torch.Size([127, 3, 256, 256])
We are at batch  23
this batch has size  torch.Size([127, 3, 256, 256])
We are at batch  24
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  25
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  26
this batch has size  torch.Size([127, 3, 256, 256])
We are at batch  27
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  28
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  29
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  30
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  31
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  32
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  33
this batch has size  torch.Size([127, 3, 256, 256])
We are at batch  34
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  35
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  36
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  37
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  38
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  39
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  40
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  41
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  42
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  43
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  44
this batch has size  torch.Size([127, 3, 256, 256])
We are at batch  45
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  46
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  47
this batch has size  torch.Size([127, 3, 256, 256])
We are at batch  48
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  49
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  50
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  51
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  52
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  53
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  54
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  55
this batch has size  torch.Size([127, 3, 256, 256])
We are at batch  56
this batch has size  torch.Size([126, 3, 256, 256])
We are at batch  57
this batch has size  torch.Size([127, 3, 256, 256])
We are at batch  58
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  59
this batch has size  torch.Size([126, 3, 256, 256])
We are at batch  60
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  61
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  62
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  63
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  64
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  65
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  66
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  67
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  68
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  69
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  70
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  71
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  72
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  73
this batch has size  torch.Size([128, 3, 256, 256])
We are at batch  74
this batch has size  torch.Size([102, 3, 256, 256])
num of triplette of probabilities is  9433
num of  S3_labels is  9433
the new data column we have now are

       photo_id  S3_label  Prob_indoor  Prob_natural  Prob_urban
0   47386036511       2.0  -146.067384    -80.056533  226.165605
1   47386038251       2.0  -184.546766    -62.174156  246.758862
2   47386039291       2.0  -113.993057    -65.118958  179.150011
3   47386040661       2.0  -152.126420    -56.406855  208.573240
4   47386048321       0.0   240.147499   -147.099608  -93.008178
5   47386064931       2.0  -368.825431    124.437545  244.419923
6   47386094261       1.0  -238.672925    185.648652   53.072303
7   47386176281       2.0     1.440025   -100.908386   99.508767
8   47386184821       2.0   -45.480280    -33.416534   78.938129
9   47386227441       2.0   -26.726782   -107.707639  134.474227
10  47386489301       1.0  -248.231221    241.441644    6.823592
11  47386496301       1.0  -257.821194    215.017403   42.845801
12  47386582181       2.0  -303.021013     57.972000  245.083439
13  47386582311       2.0  -383.384179     73.611511  309.816812
14  47386675521       2.0  -349.663751     18.540242  331.164658
15  47386858431       0.0   134.549230    -58.849803  -75.658888
16  47386858681       0.0    56.552566    -52.425554   -4.084421
17  47386859231       2.0   -13.049640    -60.084771   73.179789
18  47386954741       0.0   324.890515   -209.497022 -115.344091
19  47387007211       1.0  -256.566473    189.084735   67.517365

ValueError: ignored

remove rows with no saved image.

In [ ]:
a = pd.read_csv('resources/data10k_places365.csv')
gg = a['S3_label']
print(gg)

0       1.0
1       2.0
2       0.0
3       0.0
4       2.0
       ...
9942    2.0
9943    2.0
9944    1.0
9945    NaN
9946    1.0
Name: S3_label, Length: 9947, dtype: float64

In [ ]:
a[gg.notna()].to_csv(path_or_buf='resources/data10k_places365.csv', index=False, sep=',')